// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package com.example.reservation.stubs;

public interface GetReservationByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID de la réservation à rechercher
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID de la réservation à rechercher
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
