// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package com.example.reservation.stubs;

public interface ReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID du client (type int64)
   * </pre>
   *
   * <code>int64 clientId = 1;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <pre>
   * ID de la chambre (type int64)
   * </pre>
   *
   * <code>int64 chambreId = 2;</code>
   * @return The chambreId.
   */
  long getChambreId();

  /**
   * <pre>
   * Date de début de la réservation (format ISO 8601 recommandé)
   * </pre>
   *
   * <code>string dateDebut = 3;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <pre>
   * Date de début de la réservation (format ISO 8601 recommandé)
   * </pre>
   *
   * <code>string dateDebut = 3;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <pre>
   * Date de fin de la réservation (format ISO 8601 recommandé)
   * </pre>
   *
   * <code>string dateFin = 4;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <pre>
   * Date de fin de la réservation (format ISO 8601 recommandé)
   * </pre>
   *
   * <code>string dateFin = 4;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <pre>
   * Préférences spécifiques du client (par exemple : type de lit)
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <pre>
   * Préférences spécifiques du client (par exemple : type de lit)
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
