// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package com.example.reservation.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID de la réservation (utilisé comme chaîne pour compatibilité)
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID de la réservation (utilisé comme chaîne pour compatibilité)
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * ID du client (type int64)
   * </pre>
   *
   * <code>int64 clientId = 2;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <pre>
   * ID de la chambre (type int64)
   * </pre>
   *
   * <code>int64 chambreId = 3;</code>
   * @return The chambreId.
   */
  long getChambreId();

  /**
   * <pre>
   * Date de début de la réservation
   * </pre>
   *
   * <code>string dateDebut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <pre>
   * Date de début de la réservation
   * </pre>
   *
   * <code>string dateDebut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <pre>
   * Date de fin de la réservation
   * </pre>
   *
   * <code>string dateFin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <pre>
   * Date de fin de la réservation
   * </pre>
   *
   * <code>string dateFin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <pre>
   * Préférences spécifiques
   * </pre>
   *
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <pre>
   * Préférences spécifiques
   * </pre>
   *
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
