// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package com.example.reservation.stubs;

public interface SaveReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Détails de la réservation sauvegardée
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <pre>
   * Détails de la réservation sauvegardée
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.example.reservation.stubs.Reservation getReservation();
  /**
   * <pre>
   * Détails de la réservation sauvegardée
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   */
  com.example.reservation.stubs.ReservationOrBuilder getReservationOrBuilder();
}
