// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

package com.example.reservation.stubs;

public interface SaveReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Détails de la réservation à sauvegarder
   * </pre>
   *
   * <code>.ReservationRequest reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <pre>
   * Détails de la réservation à sauvegarder
   * </pre>
   *
   * <code>.ReservationRequest reservation = 1;</code>
   * @return The reservation.
   */
  com.example.reservation.stubs.ReservationRequest getReservation();
  /**
   * <pre>
   * Détails de la réservation à sauvegarder
   * </pre>
   *
   * <code>.ReservationRequest reservation = 1;</code>
   */
  com.example.reservation.stubs.ReservationRequestOrBuilder getReservationOrBuilder();
}
